
-- ============================================
-- Table for entity: Customer
-- Generated by CMagic v1.0
-- ============================================
CREATE TABLE CUSTOMERP (
    ID INTEGER NOT NULL,
    CODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    ADDRESS VARCHAR(256) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    STATUS VARCHAR(256) DEFAULT 'ACTIVE',
    CREATIONDATE DATE NOT NULL,
    CREDITLIMIT DECIMAL(15,2) DEFAULT 0,
    ISVIP CHAR(1) DEFAULT 'N',
    
    -- Technical metadata
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (CODE),
    CHECK (ISVIP IN ('Y', 'N'))
);

-- Indexes for frequent searches
CREATE UNIQUE INDEX CUSTOMERP_CODE_IDX ON CUSTOMERP (CODE);

-- Comments
COMMENT ON TABLE CUSTOMERP IS 'Table for Customer - Generated by CMagic';
COMMENT ON COLUMN CUSTOMERP.ID IS 'id field';
COMMENT ON COLUMN CUSTOMERP.CODE IS 'code field';
COMMENT ON COLUMN CUSTOMERP.NAME IS 'name field';
COMMENT ON COLUMN CUSTOMERP.ADDRESS IS 'address field';
COMMENT ON COLUMN CUSTOMERP.PHONE IS 'phone field';
COMMENT ON COLUMN CUSTOMERP.EMAIL IS 'email field';
COMMENT ON COLUMN CUSTOMERP.STATUS IS 'status field';
COMMENT ON COLUMN CUSTOMERP.CREATIONDATE IS 'creationDate field';
COMMENT ON COLUMN CUSTOMERP.CREDITLIMIT IS 'creditLimit field';
COMMENT ON COLUMN CUSTOMERP.ISVIP IS 'isVip field';


-- ============================================
-- Foreign Key Constraints
-- ============================================

