-- ============================================
-- CUSTOMER DDL - Generated by CMagic v1.0
-- Date: 
-- ============================================

-- Table for Customer
CREATE OR REPLACE TABLE CUSTOMER (
    ID INTEGER NOT NULL
,
    PRIMARY KEY (ID)
);

-- Index pour la clé primaire
CREATE UNIQUE INDEX CUSTOMER_PK ON CUSTOMER(ID);

-- Index pour les champs uniques

-- Commentaires sur la table et colonnes
COMMENT ON TABLE CUSTOMER IS 'Table Customer - Generated by CMagic';
COMMENT ON COLUMN CUSTOMER.ID IS 'id field';

