--  Générer SQL 
--  Version :                   	V7R4M0 190621 
--  Générée le :              	19/02/26 17:04:41 
--  Base données relation :    	CMSPW7T 
--  Option normes :          	Db2 for i 
  
CREATE TABLE DB2SAMPLE.DEPARTMENT ( 
	DEPTNO CHAR(3) CCSID 1147 NOT NULL , 
	DEPTNAME VARCHAR(36) CCSID 1147 NOT NULL , 
	MGRNO CHAR(6) CCSID 1147 DEFAULT NULL , 
	ADMRDEPT CHAR(3) CCSID 1147 NOT NULL , 
	"LOCATION" CHAR(16) CCSID 1147 DEFAULT NULL , 
	CONSTRAINT DB2SAMPLE.Q_DB2SAMPLE_DEPARTMENT_DEPTNO_00001 PRIMARY KEY( DEPTNO ) )   
	  
	RCDFMT DEPARTMENT ; 
  
ALTER TABLE DB2SAMPLE.DEPARTMENT 
	ADD CONSTRAINT DB2SAMPLE.ROD 
	FOREIGN KEY( ADMRDEPT ) 
	REFERENCES DB2SAMPLE.DEPARTMENT ( DEPTNO ) 
	ON DELETE CASCADE 
	ON UPDATE NO ACTION ; 
  
ALTER TABLE DB2SAMPLE.DEPARTMENT 
	ADD CONSTRAINT DB2SAMPLE.RDE 
	FOREIGN KEY( MGRNO ) 
	REFERENCES DB2SAMPLE.EMPLOYEE ( EMPNO ) 
	ON DELETE SET NULL 
	ON UPDATE NO ACTION ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON DB2SAMPLE.DEPARTMENT TO GIYVOVIE WITH GRANT OPTION ; 
  


select * from DB2SAMPLE.DEPARTMENT d where d.admrdept = 'A00' ;  
