**FREE
// ============================================
// TestPreservation Service - Generated by CMagic v1.0 Sprint 2
// Source: test.cmagic
// ============================================

/if not defined(TESTPRESERVATION_SERVICE)
/define TESTPRESERVATION_SERVICE

// Includes pour le service
/include 'testpreservation.rpgleinc'
/include 'CMAGIC.rpgleinc'
/include 'GLOBAL.rpgleinc'

// ========================================
// API PUBLIQUE - PROCÉDURES EXPORTÉES
// ========================================

DCL-PROC testpreservation_create EXPORT;
  DCL-PI *N IND;
    detail LIKEDS(testpreservation_detail_t) CONST;
    id LIKEDS(testpreservation_id_t);
    errors LIKEDS(GLOBAL_listError);
  END-PI;
  
  // Délégation vers implémentation locale
  RETURN testpreservation_create_local(detail : id : errors);
END-PROC;





// ========================================
// ZONE MANUELLE - PRÉSERVÉE
// ========================================
// [CMAGIC:MANUAL_START]
// *** CODE MANUEL PERSONNALISÉ ***
DCL-S businessVar VARCHAR(100);

DCL-PROC testpreservation_create_local;
  DCL-PI *N IND;
    detail LIKEDS(testpreservation_detail_t) CONST;
    id LIKEDS(testpreservation_id_t);
    errors LIKEDS(GLOBAL_listError);
  END-PI;
  
  businessVar = 'Custom logic added by developer';
  CLEAR id;
  CLEAR errors;
  RETURN *ON;
END-PROC;

// [CMAGIC:MANUAL_END]

/endif
