--  Générer SQL 
--  Version :                   	V7R4M0 190621 
--  Générée le :              	04/07/25 12:07:38 
--  Base données relation :    	CMSPW7T 
--  Option normes :          	Db2 for i 
  
CREATE TABLE DB2SAMPLE.EMPLOYEE ( 
	EMPNO CHAR(6) CCSID 1147 NOT NULL , 
	FIRSTNME VARCHAR(12) CCSID 1147 NOT NULL , 
	MIDINIT CHAR(1) CCSID 1147 NOT NULL , 
	LASTNAME VARCHAR(15) CCSID 1147 NOT NULL , 
	WORKDEPT CHAR(3) CCSID 1147 DEFAULT NULL , 
	PHONENO CHAR(4) CCSID 1147 DEFAULT NULL , 
	HIREDATE DATE DEFAULT NULL , 
	JOB CHAR(8) CCSID 1147 DEFAULT NULL , 
	EDLEVEL SMALLINT NOT NULL , 
	SEX CHAR(1) CCSID 1147 DEFAULT NULL , 
	BIRTHDATE DATE DEFAULT NULL , 
	SALARY DECIMAL(9, 2) DEFAULT NULL , 
	BONUS DECIMAL(9, 2) DEFAULT NULL , 
	COMM DECIMAL(9, 2) DEFAULT NULL , 
	CONSTRAINT DB2SAMPLE.Q_DB2SAMPLE_EMPLOYEE_EMPNO_00001 PRIMARY KEY( EMPNO ) )   
	  
	RCDFMT EMPLOYEE   ; 
  
ALTER TABLE DB2SAMPLE.EMPLOYEE 
	ADD CONSTRAINT DB2SAMPLE.RED 
	FOREIGN KEY( WORKDEPT ) 
	REFERENCES DB2SAMPLE.DEPARTMENT ( DEPTNO ) 
	ON DELETE SET NULL 
	ON UPDATE NO ACTION ; 
  
ALTER TABLE DB2SAMPLE.EMPLOYEE 
	ADD CONSTRAINT DB2SAMPLE.NUMBER 
	CHECK( PHONENO >= '0000' AND PHONENO <= '9999' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON DB2SAMPLE.EMPLOYEE TO GIYVOVIE WITH GRANT OPTION ; 
  
