{{!-- src/templates/entity.sql.tpl --}}
-- ============================================
-- {{#each entities}}{{toUpperCase this.name}}{{/each}} DDL - Generated by CMagic v1.0
-- Reproducible generation: no volatile date
-- ============================================

{{#each entities}}
-- Table for {{this.name}}
CREATE OR REPLACE TABLE {{toUpperCase this.name}} (
{{#each (expandFieldsForSql this ../structs)}}
    {{this.sqlColumnName}} {{{toSqlType this.type}}}{{{fieldConstraints this}}}{{#unless @last}},{{/unless}}
{{/each}}
{{#if this.fields}}
{{{generateConstraints this}}}
{{/if}}
);

-- Index pour la clé primaire
{{#each (expandFieldsForSql this ../structs)}}
{{#if (eq this.name 'id')}}
CREATE UNIQUE INDEX {{toUpperCase ../this.name}}_PK ON {{toUpperCase ../this.name}}({{this.sqlColumnName}});
{{/if}}
{{/each}}

-- Index pour les champs uniques
{{#each (expandFieldsForSql this ../structs)}}
{{#if this.unique}}
CREATE UNIQUE INDEX {{toUpperCase ../this.name}}_{{this.sqlColumnName}}_UK ON {{toUpperCase ../this.name}}({{this.sqlColumnName}});
{{/if}}
{{/each}}

-- Commentaires sur la table et colonnes
COMMENT ON TABLE {{toUpperCase this.name}} IS 'Table {{this.name}} - Generated by CMagic';
{{#each (expandFieldsForSql this ../structs)}}
COMMENT ON COLUMN {{toUpperCase ../this.name}}.{{this.sqlColumnName}} IS '{{this.name}} field';
{{/each}}

{{/each}}
