{{!-- src/templates/schema.sql.tpl --}}

{{#each entities}}
-- ============================================
-- Table for entity: {{this.name}}
-- Generated by CMagic v1.0
-- ============================================
CREATE TABLE {{toUpperCase this.name}}P (
  {{#each this.fields}}
    {{toUpperCase this.name}} {{toSqlType this.type}}{{{fieldConstraints this}}},
  {{/each}}
    
    -- Technical metadata
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP{{{generateConstraints this}}}
);

-- Indexes for frequent searches
{{#each this.fields}}
  {{#if this.unique}}
CREATE UNIQUE INDEX {{toUpperCase ../name}}P_{{toUpperCase this.name}}_IDX ON {{toUpperCase ../name}}P ({{toUpperCase this.name}});
  {{/if}}
{{/each}}

-- Comments
COMMENT ON TABLE {{toUpperCase this.name}}P IS 'Table for {{this.name}} - Generated by CMagic';
{{#each this.fields}}
COMMENT ON COLUMN {{toUpperCase ../name}}P.{{toUpperCase this.name}} IS '{{this.name}} field';
{{/each}}

{{/each}}

-- ============================================
-- Foreign Key Constraints
-- ============================================
{{#each entities}}
{{generateForeignKeys @root this}}
{{/each}}
