{{!-- src/templates/test.sqlrpgle.tpl --}}
**free
// ============================================
// {{lowercase this.name}} Unit Tests - Generated by CMagic v1.0
// Source: {{@root.sourceFile}}
// Reproducible generation: no volatile date
// ============================================
ctl-opt nomain
        option(*nodebugio:*srcstmt:*nounref)
        alwnull(*usrctl)
        bnddir('QC2LE':'CKOOL');

/include qinclude,TESTCASE 
/include '/usr/local/include/{{lowercase this.name}}.rpgleinc'

dcl-pr QCMDEXC extpgm;
    command char(32767) const;
    length packed(15: 5) const;
end-pr;
dcl-s gCmd varchar(256);

// ========================================
// Test Setup/Teardown
// ========================================
dcl-proc setUpSuite export;
    dcl-pi *N; 
    end-pi;
    // [CMAGIC:MANUAL_START:setUpSuite]
    // Setup global pour tous les tests
    // [CMAGIC:MANUAL_END:setUpSuite]
end-proc;

dcl-proc setUp export;
    dcl-pi *N; 
    end-pi;
    dcl-s lCmd like(gCmd);
    
    // [CMAGIC:MANUAL_START:setUp]
    // Setup avant chaque test
    // [CMAGIC:MANUAL_END:setUp]
end-proc;

dcl-proc tearDown export;
    dcl-pi *N; 
    end-pi;
    
    // [CMAGIC:MANUAL_START:tearDown]
    // Cleanup après chaque test
    // [CMAGIC:MANUAL_END:tearDown]
end-proc;

dcl-proc tearDownSuite export;
    dcl-pi *N; 
    end-pi;
    // [CMAGIC:MANUAL_START:tearDownSuite]
    // Cleanup global après tous les tests
    // [CMAGIC:MANUAL_END:tearDownSuite]
end-proc;

// ========================================
// Generated Test Cases
// ========================================

{{#each operations}}
{{#if (eq this 'CREATE')}}
// Test création {{../name}}
dcl-proc test_{{lowercase ../name}}_create_success export;
    dcl-pi *N; 
    end-pi;
    dcl-s ErrorHappened ind;
    dcl-ds lDetail likeds({{lowercase ../name}}_detail_t) inz;
    dcl-ds lId likeds({{lowercase ../name}}_id_t) inz;
    dcl-ds lErrors likeds(GLOBAL_listError) inz;
    dcl-s lOK ind;
    
    // [CMAGIC:MANUAL_START:test_{{lowercase ../name}}_create_setup]
    // Préparer les données de test pour création
    // [CMAGIC:MANUAL_END:test_{{lowercase ../name}}_create_setup]
    
    // Test création
    lOK = {{lowercase ../name}}_create(lDetail : lId : lErrors);
    
    // Vérifications
    assert(lOK : 'Creation should succeed');
    assert(lId.id > 0 : 'ID should be generated');
    
    // [CMAGIC:MANUAL_START:test_{{lowercase ../name}}_create_cleanup]
    // Cleanup spécifique au test
    // [CMAGIC:MANUAL_END:test_{{lowercase ../name}}_create_cleanup]
    
  on-exit ErrorHappened;
    if ErrorHappened;
      fail('Unexpected error in {{lowercase ../name}}_create test');
    endif;
end-proc;

dcl-proc test_{{lowercase ../name}}_create_validation_error export;
    dcl-pi *N; 
    end-pi;
    dcl-s ErrorHappened ind;
    dcl-ds lDetail likeds({{lowercase ../name}}_detail_t) inz;
    dcl-ds lId likeds({{lowercase ../name}}_id_t) inz;
    dcl-ds lErrors likeds(GLOBAL_listError) inz;
    dcl-s lOK ind;
    
    // [CMAGIC:MANUAL_START:test_{{lowercase ../name}}_create_invalid_setup]
    // Préparer des données invalides pour test validation
    // [CMAGIC:MANUAL_END:test_{{lowercase ../name}}_create_invalid_setup]
    
    // Test création avec données invalides
    lOK = {{lowercase ../name}}_create(lDetail : lId : lErrors);
    
    // Vérifications
    assert(not lOK : 'Creation should fail with invalid data');
    assert(lErrors.count > 0 : 'Should have validation errors');
    
  on-exit ErrorHappened;
    if ErrorHappened;
      fail('Unexpected error in {{lowercase ../name}}_create validation test');
    endif;
end-proc;
{{/if}}

{{#if (eq this 'DISPLAY')}}
// Test récupération {{../name}} par ID
dcl-proc test_{{lowercase ../name}}_getByID_success export;
    dcl-pi *N; 
    end-pi;
    dcl-s ErrorHappened ind;
    dcl-ds lId likeds({{lowercase ../name}}_id_t) inz;
    dcl-ds lDetail likeds({{lowercase ../name}}_detail_t) inz;
    dcl-ds lErrors likeds(GLOBAL_listError) inz;
    dcl-s lOK ind;
    
    // [CMAGIC:MANUAL_START:test_{{lowercase ../name}}_getByID_setup]
    // Préparer un ID existant pour le test
    // [CMAGIC:MANUAL_END:test_{{lowercase ../name}}_getByID_setup]
    
    // Test récupération
    lOK = {{lowercase ../name}}_getByID(lId : lDetail : lErrors);
    
    // Vérifications
    assert(lOK : 'GetByID should succeed');
    assert(lDetail.detail.id = lId.id : 'Retrieved ID should match');
    
  on-exit ErrorHappened;
    if ErrorHappened;
      fail('Unexpected error in {{lowercase ../name}}_getByID test');
    endif;
end-proc;

dcl-proc test_{{lowercase ../name}}_getByID_not_found export;
    dcl-pi *N; 
    end-pi;
    dcl-s ErrorHappened ind;
    dcl-ds lId likeds({{lowercase ../name}}_id_t) inz;
    dcl-ds lDetail likeds({{lowercase ../name}}_detail_t) inz;
    dcl-ds lErrors likeds(GLOBAL_listError) inz;
    dcl-s lOK ind;
    
    // Setup avec un ID inexistant
    lId.id = -999;
    
    // Test récupération
    lOK = {{lowercase ../name}}_getByID(lId : lDetail : lErrors);
    
    // Vérifications
    assert(not lOK : 'GetByID should fail for non-existent ID');
    
  on-exit ErrorHappened;
    if ErrorHappened;
      fail('Unexpected error in {{lowercase ../name}}_getByID not found test');
    endif;
end-proc;
{{/if}}

{{#if (eq this 'CHANGE')}}
// Test mise à jour {{../name}}
dcl-proc test_{{lowercase ../name}}_change_success export;
    dcl-pi *N; 
    end-pi;
    dcl-s ErrorHappened ind;
    dcl-ds lId likeds({{lowercase ../name}}_id_t) inz;
    dcl-ds lDetail likeds({{lowercase ../name}}_detail_t) inz;
    dcl-ds lErrors likeds(GLOBAL_listError) inz;
    dcl-s lOK ind;
    
    // [CMAGIC:MANUAL_START:test_{{lowercase ../name}}_change_setup]
    // Préparer un enregistrement existant et les modifications
    // [CMAGIC:MANUAL_END:test_{{lowercase ../name}}_change_setup]
    
    // Test mise à jour
    lOK = {{lowercase ../name}}_change(lId : lDetail : lErrors);
    
    // Vérifications
    assert(lOK : 'Change should succeed');
    
  on-exit ErrorHappened;
    if ErrorHappened;
      fail('Unexpected error in {{lowercase ../name}}_change test');
    endif;
end-proc;
{{/if}}

{{#if (eq this 'DELETE')}}
// Test suppression {{../name}}
dcl-proc test_{{lowercase ../name}}_delete_success export;
    dcl-pi *N; 
    end-pi;
    dcl-s ErrorHappened ind;
    dcl-ds lId likeds({{lowercase ../name}}_id_t) inz;
    dcl-ds lErrors likeds(GLOBAL_listError) inz;
    dcl-s lOK ind;
    
    // [CMAGIC:MANUAL_START:test_{{lowercase ../name}}_delete_setup]
    // Préparer un enregistrement à supprimer
    // [CMAGIC:MANUAL_END:test_{{lowercase ../name}}_delete_setup]
    
    // Test suppression
    lOK = {{lowercase ../name}}_delete(lId : lErrors);
    
    // Vérifications
    assert(lOK : 'Delete should succeed');
    
  on-exit ErrorHappened;
    if ErrorHappened;
      fail('Unexpected error in {{lowercase ../name}}_delete test');
    endif;
end-proc;
{{/if}}

{{#if (eq this 'SEARCH')}}
// Test recherche {{../name}}
dcl-proc test_{{lowercase ../name}}_search_firstPage export;
    dcl-pi *N; 
    end-pi;
    dcl-s ErrorHappened ind;
    dcl-ds lContext likeDS(CMAGIC_context) inz;
    dcl-s lTotalCount like(CMAGIC_totalCount);
    dcl-ds lErrors likeDS(GLOBAL_listError) inz;
    dcl-s list pointer;
    dcl-s lOK ind;
    dcl-s lTotalCountExpected like(CMAGIC_totalCount) inz(0);
    dcl-s lCount int(10);
    
    // [CMAGIC:MANUAL_START:test_{{lowercase ../name}}_search_setup]
    // Préparer les critères de recherche et données attendues
    lContext.pageSize = 10;
    lContext.pageNumber = 1;
    // [CMAGIC:MANUAL_END:test_{{lowercase ../name}}_search_setup]
    
    // Test recherche
    lOK = {{lowercase ../name}}_search(lContext : lTotalCount : list : lErrors);
    
    // Vérifications
    assert(lOK : 'Search should succeed');
    assert(lTotalCount >= 0 : 'Total count should be >= 0');
    
  on-exit ErrorHappened;
    if ErrorHappened;
      fail('Unexpected error in {{lowercase ../name}}_search test');
    endif;
end-proc;
{{/if}}
{{/each}}

// ========================================
// Manual Test Zone
// ========================================
// [CMAGIC:MANUAL_START:additional_tests]
// Zone pour tests manuels supplémentaires
// [CMAGIC:MANUAL_END:additional_tests]
