# Test automatique de l'API Testservice
# Generated by Create-NewEntity.ps1

$baseUrl = "http://localhost:44000/api/testservices"

Write-Host "Test de l'API Testservice" -ForegroundColor Green
Write-Host "URL de base: $baseUrl" -ForegroundColor Gray

# Test 1: GET collection
Write-Host "
Test 1: GET collection" -ForegroundColor Yellow
try {
    $response = Invoke-RestMethod -Uri $baseUrl -Method GET
    Write-Host "OK: GET collection reussie ($($response.Count) elements)" -ForegroundColor Green
} catch {
    Write-Host "ERREUR: GET collection - $_" -ForegroundColor Red
}

# Test 2: GET avec pagination
Write-Host "
Test 2: GET avec pagination" -ForegroundColor Yellow
try {
    $response = Invoke-RestMethod -Uri "$baseUrl?_page=1&_limit=5" -Method GET
    Write-Host "OK: GET pagine reussie" -ForegroundColor Green
} catch {
    Write-Host "ERREUR: GET pagine - $_" -ForegroundColor Red
}

# Test 3: GET avec filtre
Write-Host "
Test 3: GET avec filtre" -ForegroundColor Yellow
try {
    $response = Invoke-RestMethod -Uri "$baseUrl?testserviceno=1" -Method GET
    Write-Host "OK: GET avec filtre reussie" -ForegroundColor Green
} catch {
    Write-Host "ERREUR: GET avec filtre - $_" -ForegroundColor Red
}

Write-Host "
Tests termines" -ForegroundColor Green