
-- ============================================
-- Table for entity: Customer
-- Generated by CMagic v1.0
-- ============================================
CREATE TABLE CUSTOMERP (
    ID INTEGER NOT NULL,
    
    -- Technical metadata
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

-- Indexes for frequent searches

-- Comments
COMMENT ON TABLE CUSTOMERP IS 'Table for Customer - Generated by CMagic';
COMMENT ON COLUMN CUSTOMERP.ID IS 'id field';


-- ============================================
-- Foreign Key Constraints
-- ============================================

